spring:
  application:
    name: poi-service
  cloud:
    config:
      discovery:
        enabled: true
management.security.enabled: false

eureka:
 instance:
  hostname: epsilon

stores:
  ribbon:
    listOfServers: ryandel.selfhost.me
    
ribbon:
  eureka:
    enabled: false